version: '2'
services:
  python:
    image: vijay/python-redis:1
    container_name: python
    environment:
      - "redis_host=redis"
    ports:
     - "8080:5000"
    networks:
      - network1-app
  redis:
    container_name: redis
    image: "redis"
    networks:
      - network1-app
networks:
  network1-app:
    driver: bridge
