version: '2'

services:

  nginx:
    image: "nginx"
    ports:
     - "8070:80"

    networks:
      - network1-app

  redis:
    image: "redis"

    networks:
      - network1-app
networks:
  network1-app:
    driver: bridge
